name: afiq_s_application2
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: ">=3.0.2 <4.0.0"
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_bloc: ^8.0.0
  connectivity_plus: 5.0.1
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  equatable: ^2.0.0
  flutter_rating_bar: ^4.0.0
  readmore: ^2.1.0
  google_maps_flutter: ^2.0.0
  material: any
  amplify_api: ^1.0.0
  amplify_auth_cognito: ^1.0.0
  amplify_authenticator: ^1.0.0
  amplify_flutter: ^1.0.0
  amplify_storage_s3: ^1.0.0
  cupertino_icons: ^1.0.5
  flutter_riverpod: ^2.1.3
  go_router: ^7.0.0
  image_picker: ^0.8.0
  intl: ^0.18.0
  path: ^1.8.3
  riverpod_annotation: ^2.0.1
  uuid: ^3.0.7
dev_dependencies: 
  amplify_lints: ^3.0.0
  build_runner:
  custom_lint:
  flutter_test: 
    sdk: flutter
  riverpod_generator: ^2.1.3
  riverpod_lint: ^1.1.5

flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterBlackItalic.ttf
          weight: 900
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
